Prevent vcvarsall.bat from changing current directory
Building with VS2017 15.3.5 produces following error:

c1: fatal error C1083: Cannot open source file: 'yyacc.c': No such file or directory

This happens because vsdevcmd_end.bat changes current directory to %USERPROFILE%\Source if it exists.